// <auto-generated />
namespace DentalClinicManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_AppointmentEmail_And_PatientEmail_To_Respective_DBs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_AppointmentEmail_And_PatientEmail_To_Respective_DBs));
        
        string IMigrationMetadata.Id
        {
            get { return "202210220714254_Add_AppointmentEmail_And_PatientEmail_To_Respective_DBs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
